// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Login.proto
// Protobuf C++ Version: 5.29.5

#ifndef Login_2eproto_2epb_2eh
#define Login_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Login_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Login_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Login_2eproto;
namespace Protocol {
class S2C_TEST;
struct S2C_TESTDefaultTypeInternal;
extern S2C_TESTDefaultTypeInternal _S2C_TEST_default_instance_;
}  // namespace Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Protocol {

// ===================================================================


// -------------------------------------------------------------------

class S2C_TEST final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.S2C_TEST) */ {
 public:
  inline S2C_TEST() : S2C_TEST(nullptr) {}
  ~S2C_TEST() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(S2C_TEST* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(S2C_TEST));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR S2C_TEST(
      ::google::protobuf::internal::ConstantInitialized);

  inline S2C_TEST(const S2C_TEST& from) : S2C_TEST(nullptr, from) {}
  inline S2C_TEST(S2C_TEST&& from) noexcept
      : S2C_TEST(nullptr, std::move(from)) {}
  inline S2C_TEST& operator=(const S2C_TEST& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2C_TEST& operator=(S2C_TEST&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2C_TEST& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2C_TEST* internal_default_instance() {
    return reinterpret_cast<const S2C_TEST*>(
        &_S2C_TEST_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(S2C_TEST& a, S2C_TEST& b) { a.Swap(&b); }
  inline void Swap(S2C_TEST* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2C_TEST* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2C_TEST* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<S2C_TEST>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const S2C_TEST& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const S2C_TEST& from) { S2C_TEST::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(S2C_TEST* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.S2C_TEST"; }

 protected:
  explicit S2C_TEST(::google::protobuf::Arena* arena);
  S2C_TEST(::google::protobuf::Arena* arena, const S2C_TEST& from);
  S2C_TEST(::google::protobuf::Arena* arena, S2C_TEST&& from) noexcept
      : S2C_TEST(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
    kHpFieldNumber = 2,
    kAttackFieldNumber = 3,
    kTestFieldNumber = 4,
  };
  // uint64 id = 1;
  void clear_id() ;
  ::uint64_t id() const;
  void set_id(::uint64_t value);

  private:
  ::uint64_t _internal_id() const;
  void _internal_set_id(::uint64_t value);

  public:
  // uint32 hp = 2;
  void clear_hp() ;
  ::uint32_t hp() const;
  void set_hp(::uint32_t value);

  private:
  ::uint32_t _internal_hp() const;
  void _internal_set_hp(::uint32_t value);

  public:
  // uint32 attack = 3;
  void clear_attack() ;
  ::uint32_t attack() const;
  void set_attack(::uint32_t value);

  private:
  ::uint32_t _internal_attack() const;
  void _internal_set_attack(::uint32_t value);

  public:
  // uint32 test = 4;
  void clear_test() ;
  ::uint32_t test() const;
  void set_test(::uint32_t value);

  private:
  ::uint32_t _internal_test() const;
  void _internal_set_test(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.S2C_TEST)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const S2C_TEST& from_msg);
    ::uint64_t id_;
    ::uint32_t hp_;
    ::uint32_t attack_;
    ::uint32_t test_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Login_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// S2C_TEST

// uint64 id = 1;
inline void S2C_TEST::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = ::uint64_t{0u};
}
inline ::uint64_t S2C_TEST::id() const {
  // @@protoc_insertion_point(field_get:Protocol.S2C_TEST.id)
  return _internal_id();
}
inline void S2C_TEST::set_id(::uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Protocol.S2C_TEST.id)
}
inline ::uint64_t S2C_TEST::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void S2C_TEST::_internal_set_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// uint32 hp = 2;
inline void S2C_TEST::clear_hp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hp_ = 0u;
}
inline ::uint32_t S2C_TEST::hp() const {
  // @@protoc_insertion_point(field_get:Protocol.S2C_TEST.hp)
  return _internal_hp();
}
inline void S2C_TEST::set_hp(::uint32_t value) {
  _internal_set_hp(value);
  // @@protoc_insertion_point(field_set:Protocol.S2C_TEST.hp)
}
inline ::uint32_t S2C_TEST::_internal_hp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.hp_;
}
inline void S2C_TEST::_internal_set_hp(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hp_ = value;
}

// uint32 attack = 3;
inline void S2C_TEST::clear_attack() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.attack_ = 0u;
}
inline ::uint32_t S2C_TEST::attack() const {
  // @@protoc_insertion_point(field_get:Protocol.S2C_TEST.attack)
  return _internal_attack();
}
inline void S2C_TEST::set_attack(::uint32_t value) {
  _internal_set_attack(value);
  // @@protoc_insertion_point(field_set:Protocol.S2C_TEST.attack)
}
inline ::uint32_t S2C_TEST::_internal_attack() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.attack_;
}
inline void S2C_TEST::_internal_set_attack(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.attack_ = value;
}

// uint32 test = 4;
inline void S2C_TEST::clear_test() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.test_ = 0u;
}
inline ::uint32_t S2C_TEST::test() const {
  // @@protoc_insertion_point(field_get:Protocol.S2C_TEST.test)
  return _internal_test();
}
inline void S2C_TEST::set_test(::uint32_t value) {
  _internal_set_test(value);
  // @@protoc_insertion_point(field_set:Protocol.S2C_TEST.test)
}
inline ::uint32_t S2C_TEST::_internal_test() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.test_;
}
inline void S2C_TEST::_internal_set_test(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.test_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Login_2eproto_2epb_2eh
