// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Login.proto
// Protobuf C++ Version: 5.29.5

#include "Login.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Protocol {

inline constexpr S2C_TEST::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{::uint64_t{0u}},
        hp_{0u},
        attack_{0u},
        test_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR S2C_TEST::S2C_TEST(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct S2C_TESTDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S2C_TESTDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~S2C_TESTDefaultTypeInternal() {}
  union {
    S2C_TEST _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S2C_TESTDefaultTypeInternal _S2C_TEST_default_instance_;
}  // namespace Protocol
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Login_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Login_2eproto = nullptr;
const ::uint32_t
    TableStruct_Login_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Protocol::S2C_TEST, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Protocol::S2C_TEST, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::Protocol::S2C_TEST, _impl_.hp_),
        PROTOBUF_FIELD_OFFSET(::Protocol::S2C_TEST, _impl_.attack_),
        PROTOBUF_FIELD_OFFSET(::Protocol::S2C_TEST, _impl_.test_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Protocol::S2C_TEST)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::Protocol::_S2C_TEST_default_instance_._instance,
};
const char descriptor_table_protodef_Login_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013Login.proto\022\010Protocol\"@\n\010S2C_TEST\022\n\n\002i"
    "d\030\001 \001(\004\022\n\n\002hp\030\002 \001(\r\022\016\n\006attack\030\003 \001(\r\022\014\n\004t"
    "est\030\004 \001(\rb\006proto3"
};
static ::absl::once_flag descriptor_table_Login_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Login_2eproto = {
    false,
    false,
    97,
    descriptor_table_protodef_Login_2eproto,
    "Login.proto",
    &descriptor_table_Login_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_Login_2eproto::offsets,
    file_level_enum_descriptors_Login_2eproto,
    file_level_service_descriptors_Login_2eproto,
};
namespace Protocol {
// ===================================================================

class S2C_TEST::_Internal {
 public:
};

S2C_TEST::S2C_TEST(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.S2C_TEST)
}
S2C_TEST::S2C_TEST(
    ::google::protobuf::Arena* arena, const S2C_TEST& from)
    : S2C_TEST(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE S2C_TEST::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void S2C_TEST::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, test_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::test_));
}
S2C_TEST::~S2C_TEST() {
  // @@protoc_insertion_point(destructor:Protocol.S2C_TEST)
  SharedDtor(*this);
}
inline void S2C_TEST::SharedDtor(MessageLite& self) {
  S2C_TEST& this_ = static_cast<S2C_TEST&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* S2C_TEST::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) S2C_TEST(arena);
}
constexpr auto S2C_TEST::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(S2C_TEST),
                                            alignof(S2C_TEST));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull S2C_TEST::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_S2C_TEST_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &S2C_TEST::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<S2C_TEST>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &S2C_TEST::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<S2C_TEST>(), &S2C_TEST::ByteSizeLong,
            &S2C_TEST::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(S2C_TEST, _impl_._cached_size_),
        false,
    },
    &S2C_TEST::kDescriptorMethods,
    &descriptor_table_Login_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* S2C_TEST::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2> S2C_TEST::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::S2C_TEST>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 test = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(S2C_TEST, _impl_.test_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(S2C_TEST, _impl_.test_)}},
    // uint64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(S2C_TEST, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(S2C_TEST, _impl_.id_)}},
    // uint32 hp = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(S2C_TEST, _impl_.hp_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(S2C_TEST, _impl_.hp_)}},
    // uint32 attack = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(S2C_TEST, _impl_.attack_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(S2C_TEST, _impl_.attack_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 id = 1;
    {PROTOBUF_FIELD_OFFSET(S2C_TEST, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint32 hp = 2;
    {PROTOBUF_FIELD_OFFSET(S2C_TEST, _impl_.hp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 attack = 3;
    {PROTOBUF_FIELD_OFFSET(S2C_TEST, _impl_.attack_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 test = 4;
    {PROTOBUF_FIELD_OFFSET(S2C_TEST, _impl_.test_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void S2C_TEST::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.S2C_TEST)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.test_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.test_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* S2C_TEST::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const S2C_TEST& this_ = static_cast<const S2C_TEST&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* S2C_TEST::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const S2C_TEST& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Protocol.S2C_TEST)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 id = 1;
          if (this_._internal_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_id(), target);
          }

          // uint32 hp = 2;
          if (this_._internal_hp() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_hp(), target);
          }

          // uint32 attack = 3;
          if (this_._internal_attack() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                3, this_._internal_attack(), target);
          }

          // uint32 test = 4;
          if (this_._internal_test() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                4, this_._internal_test(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Protocol.S2C_TEST)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t S2C_TEST::ByteSizeLong(const MessageLite& base) {
          const S2C_TEST& this_ = static_cast<const S2C_TEST&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t S2C_TEST::ByteSizeLong() const {
          const S2C_TEST& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Protocol.S2C_TEST)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // uint64 id = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_id());
            }
            // uint32 hp = 2;
            if (this_._internal_hp() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_hp());
            }
            // uint32 attack = 3;
            if (this_._internal_attack() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_attack());
            }
            // uint32 test = 4;
            if (this_._internal_test() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_test());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void S2C_TEST::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<S2C_TEST*>(&to_msg);
  auto& from = static_cast<const S2C_TEST&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.S2C_TEST)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  if (from._internal_hp() != 0) {
    _this->_impl_.hp_ = from._impl_.hp_;
  }
  if (from._internal_attack() != 0) {
    _this->_impl_.attack_ = from._impl_.attack_;
  }
  if (from._internal_test() != 0) {
    _this->_impl_.test_ = from._impl_.test_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void S2C_TEST::CopyFrom(const S2C_TEST& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.S2C_TEST)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void S2C_TEST::InternalSwap(S2C_TEST* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(S2C_TEST, _impl_.test_)
      + sizeof(S2C_TEST::_impl_.test_)
      - PROTOBUF_FIELD_OFFSET(S2C_TEST, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata S2C_TEST::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_Login_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
