// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PacketId.proto
// Protobuf C++ Version: 5.29.5

#include "PacketId.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Protocol {
}  // namespace Protocol
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_PacketId_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_PacketId_2eproto = nullptr;
const ::uint32_t TableStruct_PacketId_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_PacketId_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016PacketId.proto\022\010Protocol*\\\n\tePacketId\022"
    "\014\n\010PKT_NONE\020\000\022\026\n\021PKT_C2S_LOGIN_REQ\020\350\007\022\026\n"
    "\021PKT_S2C_LOGIN_RES\020\351\007\022\021\n\014PKT_C2S_MOVE\020\320\017"
    "b\006proto3"
};
static ::absl::once_flag descriptor_table_PacketId_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_PacketId_2eproto = {
    false,
    false,
    128,
    descriptor_table_protodef_PacketId_2eproto,
    "PacketId.proto",
    &descriptor_table_PacketId_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_PacketId_2eproto::offsets,
    file_level_enum_descriptors_PacketId_2eproto,
    file_level_service_descriptors_PacketId_2eproto,
};
namespace Protocol {
const ::google::protobuf::EnumDescriptor* ePacketId_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_PacketId_2eproto);
  return file_level_enum_descriptors_PacketId_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ePacketId_internal_data_[] = {
    65536u, 196608u, 1001u, 1000u, 2000u, };
bool ePacketId_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, ePacketId_internal_data_);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_PacketId_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
